/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrarMezquitaRouteImport } from './routes/registrar-mezquita'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsuariosRouteImport } from './routes/_app/usuarios'
import { Route as AppShartRouteImport } from './routes/_app/shart'
import { Route as AppRamadanRouteImport } from './routes/_app/ramadan'
import { Route as AppMezquitasRouteImport } from './routes/_app/mezquitas'
import { Route as AppIngresosRouteImport } from './routes/_app/ingresos'
import { Route as AppGastosRouteImport } from './routes/_app/gastos'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAulasRouteImport } from './routes/_app/aulas'
import { Route as AppAlumnosRouteImport } from './routes/_app/alumnos'
import { Route as AppAlumnosIndexRouteImport } from './routes/_app/alumnos.index'
import { Route as AppMezquitasMosqueIdRouteImport } from './routes/_app/mezquitas.$mosqueId'
import { Route as AppAlumnosStudentIdRouteImport } from './routes/_app/alumnos.$studentId'

const RegistrarMezquitaRoute = RegistrarMezquitaRouteImport.update({
  id: '/registrar-mezquita',
  path: '/registrar-mezquita',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppShartRoute = AppShartRouteImport.update({
  id: '/shart',
  path: '/shart',
  getParentRoute: () => AppRoute,
} as any)
const AppRamadanRoute = AppRamadanRouteImport.update({
  id: '/ramadan',
  path: '/ramadan',
  getParentRoute: () => AppRoute,
} as any)
const AppMezquitasRoute = AppMezquitasRouteImport.update({
  id: '/mezquitas',
  path: '/mezquitas',
  getParentRoute: () => AppRoute,
} as any)
const AppIngresosRoute = AppIngresosRouteImport.update({
  id: '/ingresos',
  path: '/ingresos',
  getParentRoute: () => AppRoute,
} as any)
const AppGastosRoute = AppGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAulasRoute = AppAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AppRoute,
} as any)
const AppAlumnosRoute = AppAlumnosRouteImport.update({
  id: '/alumnos',
  path: '/alumnos',
  getParentRoute: () => AppRoute,
} as any)
const AppAlumnosIndexRoute = AppAlumnosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAlumnosRoute,
} as any)
const AppMezquitasMosqueIdRoute = AppMezquitasMosqueIdRouteImport.update({
  id: '/$mosqueId',
  path: '/$mosqueId',
  getParentRoute: () => AppMezquitasRoute,
} as any)
const AppAlumnosStudentIdRoute = AppAlumnosStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => AppAlumnosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/registrar-mezquita': typeof RegistrarMezquitaRoute
  '/alumnos': typeof AppAlumnosRouteWithChildren
  '/aulas': typeof AppAulasRoute
  '/dashboard': typeof AppDashboardRoute
  '/gastos': typeof AppGastosRoute
  '/ingresos': typeof AppIngresosRoute
  '/mezquitas': typeof AppMezquitasRouteWithChildren
  '/ramadan': typeof AppRamadanRoute
  '/shart': typeof AppShartRoute
  '/usuarios': typeof AppUsuariosRoute
  '/alumnos/$studentId': typeof AppAlumnosStudentIdRoute
  '/mezquitas/$mosqueId': typeof AppMezquitasMosqueIdRoute
  '/alumnos/': typeof AppAlumnosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/registrar-mezquita': typeof RegistrarMezquitaRoute
  '/aulas': typeof AppAulasRoute
  '/dashboard': typeof AppDashboardRoute
  '/gastos': typeof AppGastosRoute
  '/ingresos': typeof AppIngresosRoute
  '/mezquitas': typeof AppMezquitasRouteWithChildren
  '/ramadan': typeof AppRamadanRoute
  '/shart': typeof AppShartRoute
  '/usuarios': typeof AppUsuariosRoute
  '/alumnos/$studentId': typeof AppAlumnosStudentIdRoute
  '/mezquitas/$mosqueId': typeof AppMezquitasMosqueIdRoute
  '/alumnos': typeof AppAlumnosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/registrar-mezquita': typeof RegistrarMezquitaRoute
  '/_app/alumnos': typeof AppAlumnosRouteWithChildren
  '/_app/aulas': typeof AppAulasRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/gastos': typeof AppGastosRoute
  '/_app/ingresos': typeof AppIngresosRoute
  '/_app/mezquitas': typeof AppMezquitasRouteWithChildren
  '/_app/ramadan': typeof AppRamadanRoute
  '/_app/shart': typeof AppShartRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/alumnos/$studentId': typeof AppAlumnosStudentIdRoute
  '/_app/mezquitas/$mosqueId': typeof AppMezquitasMosqueIdRoute
  '/_app/alumnos/': typeof AppAlumnosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/registrar-mezquita'
    | '/alumnos'
    | '/aulas'
    | '/dashboard'
    | '/gastos'
    | '/ingresos'
    | '/mezquitas'
    | '/ramadan'
    | '/shart'
    | '/usuarios'
    | '/alumnos/$studentId'
    | '/mezquitas/$mosqueId'
    | '/alumnos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/registrar-mezquita'
    | '/aulas'
    | '/dashboard'
    | '/gastos'
    | '/ingresos'
    | '/mezquitas'
    | '/ramadan'
    | '/shart'
    | '/usuarios'
    | '/alumnos/$studentId'
    | '/mezquitas/$mosqueId'
    | '/alumnos'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/change-password'
    | '/login'
    | '/registrar-mezquita'
    | '/_app/alumnos'
    | '/_app/aulas'
    | '/_app/dashboard'
    | '/_app/gastos'
    | '/_app/ingresos'
    | '/_app/mezquitas'
    | '/_app/ramadan'
    | '/_app/shart'
    | '/_app/usuarios'
    | '/_app/alumnos/$studentId'
    | '/_app/mezquitas/$mosqueId'
    | '/_app/alumnos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  RegistrarMezquitaRoute: typeof RegistrarMezquitaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registrar-mezquita': {
      id: '/registrar-mezquita'
      path: '/registrar-mezquita'
      fullPath: '/registrar-mezquita'
      preLoaderRoute: typeof RegistrarMezquitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shart': {
      id: '/_app/shart'
      path: '/shart'
      fullPath: '/shart'
      preLoaderRoute: typeof AppShartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ramadan': {
      id: '/_app/ramadan'
      path: '/ramadan'
      fullPath: '/ramadan'
      preLoaderRoute: typeof AppRamadanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mezquitas': {
      id: '/_app/mezquitas'
      path: '/mezquitas'
      fullPath: '/mezquitas'
      preLoaderRoute: typeof AppMezquitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingresos': {
      id: '/_app/ingresos'
      path: '/ingresos'
      fullPath: '/ingresos'
      preLoaderRoute: typeof AppIngresosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gastos': {
      id: '/_app/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof AppGastosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aulas': {
      id: '/_app/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AppAulasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alumnos': {
      id: '/_app/alumnos'
      path: '/alumnos'
      fullPath: '/alumnos'
      preLoaderRoute: typeof AppAlumnosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alumnos/': {
      id: '/_app/alumnos/'
      path: '/'
      fullPath: '/alumnos/'
      preLoaderRoute: typeof AppAlumnosIndexRouteImport
      parentRoute: typeof AppAlumnosRoute
    }
    '/_app/mezquitas/$mosqueId': {
      id: '/_app/mezquitas/$mosqueId'
      path: '/$mosqueId'
      fullPath: '/mezquitas/$mosqueId'
      preLoaderRoute: typeof AppMezquitasMosqueIdRouteImport
      parentRoute: typeof AppMezquitasRoute
    }
    '/_app/alumnos/$studentId': {
      id: '/_app/alumnos/$studentId'
      path: '/$studentId'
      fullPath: '/alumnos/$studentId'
      preLoaderRoute: typeof AppAlumnosStudentIdRouteImport
      parentRoute: typeof AppAlumnosRoute
    }
  }
}

interface AppAlumnosRouteChildren {
  AppAlumnosStudentIdRoute: typeof AppAlumnosStudentIdRoute
  AppAlumnosIndexRoute: typeof AppAlumnosIndexRoute
}

const AppAlumnosRouteChildren: AppAlumnosRouteChildren = {
  AppAlumnosStudentIdRoute: AppAlumnosStudentIdRoute,
  AppAlumnosIndexRoute: AppAlumnosIndexRoute,
}

const AppAlumnosRouteWithChildren = AppAlumnosRoute._addFileChildren(
  AppAlumnosRouteChildren,
)

interface AppMezquitasRouteChildren {
  AppMezquitasMosqueIdRoute: typeof AppMezquitasMosqueIdRoute
}

const AppMezquitasRouteChildren: AppMezquitasRouteChildren = {
  AppMezquitasMosqueIdRoute: AppMezquitasMosqueIdRoute,
}

const AppMezquitasRouteWithChildren = AppMezquitasRoute._addFileChildren(
  AppMezquitasRouteChildren,
)

interface AppRouteChildren {
  AppAlumnosRoute: typeof AppAlumnosRouteWithChildren
  AppAulasRoute: typeof AppAulasRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGastosRoute: typeof AppGastosRoute
  AppIngresosRoute: typeof AppIngresosRoute
  AppMezquitasRoute: typeof AppMezquitasRouteWithChildren
  AppRamadanRoute: typeof AppRamadanRoute
  AppShartRoute: typeof AppShartRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlumnosRoute: AppAlumnosRouteWithChildren,
  AppAulasRoute: AppAulasRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGastosRoute: AppGastosRoute,
  AppIngresosRoute: AppIngresosRoute,
  AppMezquitasRoute: AppMezquitasRouteWithChildren,
  AppRamadanRoute: AppRamadanRoute,
  AppShartRoute: AppShartRoute,
  AppUsuariosRoute: AppUsuariosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  RegistrarMezquitaRoute: RegistrarMezquitaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
